server:
  port: 8080
#  指定端口号

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cat_catcher?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis 原生配置（关键！）
mybatis:
  # 指定 Mapper XML 文件位置（可选，如果你用注解可省略）
  mapper-locations: classpath:mapper/*.xml
  # 指定实体类别名包（避免写全限定名）
  type-aliases-package: com.github.computer114514.pojo
  # 开启驼峰映射（数据库 user_id → Java userId）
  configuration:
    map-underscore-to-camel-case: true